### ISSUE TITLE
App crashes on Huawei Y5 2018 running Android 8.1

### ISSUE THREAD

**Issue by julian0521** [apache/cordova-plugin-camera#445]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
The app crashes after click on accept button with the picture taken.

### Environment, Platform, Device

Android 8.1 - Huawei Y5 2018

### Version information

 ionic (Ionic CLI) : 4.10.2
cordova: 8.1.2 (cordova-lib@8.1.1)
npm: 6.4.1
cordova-plugin-camera: 2.4.1

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by jpike88** [comment]
Had this problem on a OnePlus

**Comment by julian0521** [comment]
bug fixed with library update cordova-plugin-camera to 4.0.3

**Comment by anguis-datura** [comment]
> bug fixed with library update cordova-plugin-camera to 4.0.3
Issue wasn't closed so bug is still there, isn't it? I see such crashes.

**Comment by abrahamnm** [comment]
Any updates on this? I'm having a similar issue with the same device. The camera never opens and the app crashes.

Device:
 **Android 8.1 - Huawei Y5 2018**
plugin:
**"cordova-plugin-camera": "^4.1.0"**

**Comment by PieterVanPoyer** [comment]
Is this issue still present with the latest version?

**Comment by PieterVanPoyer** [comment]
Closing due to a lack of response. Issue is most likely not occuring in the latest release.
