### ISSUE TITLE
Not working for Android 11

### ISSUE THREAD

**Issue by Houdhey** [apache/cordova-plugin-camera#707]
# Bug Report

## Problem
My app was working well with Camera, until I tested on Android 11 emulator.  Is there something new to do to make it work for Android 11? Like adding something on Manifest...?

### What is expected to happen?
Open the camera.

### What does actually happen?
Nothing and no error message.

EDIT: After updating the plugin, i get this error on console : 
```cannot open camera:  length=1; index=1```

And from Android Studio : 
`V/Capacitor/Plugin: To native (Cordova plugin): callbackId: Camera662807201, service: Camera, action: takePicture, actionArgs: [100,0,1,-1,-1,0,0,false,true,false,null,0]
E/PluginManager: Uncaught exception from plugin
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at org.apache.cordova.camera.CordovaUri.getFileNameFromUri(CordovaUri.java:97)
        at org.apache.cordova.camera.CordovaUri.<init>(CordovaUri.java:51)
        at org.apache.cordova.camera.CameraLauncher.takePicture(CameraLauncher.java:303)
        at org.apache.cordova.camera.CameraLauncher.callTakePicture(CameraLauncher.java:282)
        at org.apache.cordova.camera.CameraLauncher.execute(CameraLauncher.java:190)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:69)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:45)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.os.HandlerThread.run(HandlerThread.java:67)
I/Capacitor/Console: File: http://localhost/main-es2015.js - Line 16537 - Msg: cannot open camera:  length=1; index=1`

### Command or Code
```takeImage() {
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.DATA_URL,
      mediaType: this.camera.MediaType.PICTURE,
      encodingType: this.camera.EncodingType.JPEG,
      correctOrientation: true,
      allowEdit: false,
    };


    this.camera.getPicture(options).then(
      (imageData) => {
        console.log('image Data ' + JSON.stringify(imageData));```



### Environment, Platform, Device
Android 11, device : emulator Pixel 3A with Android 11

**Comment by sebastian-curland** [comment]
I'm getting access denied on Android 11 devices when I try to select a picture from gallery or when I use the camera.
I tried some of the workarounds out there, like targeting to API level 29 and adding `requestLegacyExternalStorage="true"` to the AndroidManifest but it didn't work for me.

Does anyone knows how to get this plugin working in Android 11?

BTW - is there any plan to fix the plugin to work with Android 11 `scoped storage`?

**Comment by djdannycastillo** [comment]
I have a similar error.

This plugin works like a charm when I select images from gallery in android 10 but when I'm trying to select a video, it doesn't work, It appears a "EACCES (Permission denied)" error.

I'm using
cordova-plugin-camera 4.1.0
cordova-android 9.0.0

Any solution?

**Comment by sebastian-curland** [comment]
@djdannycastillo for me it started to work once I disabled the editing of the image in the plugin options (and with `requestLegacyExternalStorage="true"`).

**Comment by Houdhey** [comment]
@djdannycastillo  I also have this problem with Android 10 now.  Not the same errror, it's weird.
It's an error like : 
```E/chromium: [ERROR:aw_browser_terminator.cc(123)] Renderer process crash detected (code -1).
E/chromium: ... Render process kill wasn't handed by all associated webviews, killing application
```
The app can open the camera, but when I will exactly click to take a photo, this error appears, and the app restarts.

**Comment by djdannycastillo** [comment]
> @djdannycastillo for me it started to work once I disabled the editing of the image in the plugin options (and with `requestLegacyExternalStorage="true"`).

The issue is solved with `requestLegacyExternalStorage="true"` thanks @sebastian-curland

**Comment by djdannycastillo** [comment]
@Houdhey maybe this can help you #434

**Comment by Houdhey** [comment]
> @Houdhey maybe this can help you #434

Thanks, but I've already seen it and it didn't help. Still the same problem. We can't deliver our app to our client because of this. Same problem for many Ionic plugins, Android 11 broke everything. But these plugins should adapt, Android 11 was deployed in September 2020.
I'm looking for a solution which doesn't use plugin

**Comment by Houdhey** [comment]
The problem comes from the ```getFileNameFromUri(Uri uri)``` method in the ```CordovaUri.java```. 
Especially when doing this method: ```String partial_path = fullUri.split("external_files")[1];```, it gives ```java.lang.ArrayIndexOutOfBoundsException: length=1; index=1```

**Comment by Houdhey** [comment]
Using https://ionicframework.com/docs/native/media-capture works fine for Android 11. My app opens camera. If you need inspiration for fix this problem, maybe you should have a look at this plugin

**Comment by jfoclpf** [comment]
@Houdhey why not make a PR to this repo and help others?
